name: Publish LaTeX documents
on: [push, pull_request, workflow_dispatch]
jobs:
  build_latex:
    strategy:
      fail-fast: true
      matrix:
        include:
          - source: "./user_documentation/root.tex"
            out: "2024_UD1_Chromacase.pdf"
            name: "User Documentation"
          - source: "./tech_documentation/root.tex"
            out: "2024_TD1_Chromacase.pdf"
            name: "Technical Documentation"
    name: "Build ${{ matrix.name }}"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.source }}
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
      - name: Rename output
        run: |
          mv "root.pdf" ${{ matrix.out }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 2024_DA2_Chromacase
          path: ${{ matrix.out }}