name: Build and Publish LaTeX documents
on: [push, pull_request, workflow_dispatch]
jobs:
  build_latex:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: true
      matrix:
        include:
          - source: "2024_UD2_Chromacase.tex"
            name: "User Documentation"
          - source: "2024_TD2_Chromacase.tex"
            name: "Technical Documentation"
    name: "Build ${{ matrix.name }}"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.source }}
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 2024_DA2_Chromacase
          path: |
            ./2024*.pdf
  publish:
    runs-on: ubuntu-latest
    needs: build_latex
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: 2024_DA2_Chromacase
      - name: Clone SVN
        run: svn co "${{ secrets.SVN_URL }}" svn --username '${{ secrets.SVN_UNAME }}' --password '${{ secrets.SVN_PWD }}'
      - name: Move Generated files
        run: mv *.pdf svn/rendu
      - name: Commit files
        run: |
          cd svn/rendu
          svn add --force .;
          svn commit -m 'DA2: ${{ github.event.head_commit.message }}' --username '${{ secrets.SVN_UNAME }}' --password '${{ secrets.SVN_PWD }}'

